export type MapSet = {
    id: number;
    creator_id: number;
    creator_username: string;
    artist: string;
    title: string;
    source: string;
    tags: string;
    description: string | null;
    ranked_status: number;
    date_submitted: string;
    date_last_updated: string;
    bpms: number[];
    game_modes: number[];
    difficulty_names: string[];
    difficulty_range: number[];
    min_length_seconds: number;
    max_length_seconds: number;
    min_ln_percent: number;
    max_ln_percent: number;
    min_play_count: number;
    max_play_count: number;
    min_date_submitted: string;
    max_date_submitted: string;
    min_date_last_updated: string;
    max_date_last_updated: string;
    min_combo: number;
    max_combo: number;
};
